### ISSUE TITLE
spacers

### ISSUE THREAD

**Issue by juanfal** [facelessuser/ExportHtml#33]
Hi

I consider, since it appeared, ExportHTML, the best companion for ST2/3, without it I don't know the amount of time I would have wasted copying pasting in another places or doing weird things to have the source code coloured.  And it is amazingly supported, thanks!!

There is one glitch that has been annoying me a bit since long time ago.  I usually create a HTML output not for the file, nor for the real HTML, but to copy/paste parts of it as answers to my students.  The best situation for this is ST3/Safari/Mail.  The issue here is when having in the original source file a space, but splitting two different things, different colours, ExportHTML generates a HTML entity that is not a real space:
![captura de pantalla 2015-07-28 a las 9 18 45](https://cloud.githubusercontent.com/assets/895596/8925674/eb626342-3509-11e5-88ef-71de5b307587.png)

then, copy/pasting it in Mail it gets joint, and look a bit dirty and ugly:

![captura de pantalla 2015-07-28 a las 9 21 39](https://cloud.githubusercontent.com/assets/895596/8925686/14bd0a80-350a-11e5-97dd-8f2cb78806dc.png)

If the student copy/paste the code in their editors won't have any space in between either.

Is there any solution for this problem?

Thanks in advance

**Comment by facelessuser** [comment]
This is tricky.  I am using a non breaking space `&nbsp;`.  I could wrap each line in a `<code>` tag and eliminate the `&nbsp;`, but then it breaks MS Outlook copy and paste for me at work; everything looses its indentation and such.  It is kind of the same issue you see, but for the opposite reason.  That puts me changing things in opposition to each other.  I can break Outlook, or I can break Safari/Mail.

In my use cases, copy and paste from  Chrome to Gmail or Outlook works fine, but it appears Apple is doing things a little different (I have a Mac as well, but I use neither Safari or Mail).

Part of the this is due to my approach.  Because I am using a table, it makes things...more complicated.  But using a table is the best way for me to keep line numbers **and** wrapping for HTML printing (as a side note I also have people who have use cases that desire eliminating the tabled output; can't please everybody :smile:).  If I did things simple with a simple `<pre><code></code></pre>` this would be much easier, but then you loose the line numbers with wrapping.

What to do...

I guess it is possible I could abstract this logic for whitespace and provide a setting that alters the printing style to the users desired format.

method 1:

```
<span>Hello</span><span>&nbsp;</span><span>World</span>
```

or method2:

```
<code><span>Hello</span><span> </span><span>World</span>
```

Assuming that this works for you in Safari/Mail that is.  I need to experiment with some options.  Ideally if I could bridge the the two and have one solution without having to abstract the logic, that would be ideal. I'd love to kill the `&nbsp;` but I wrote this to plugin to aid in my current workflow at my job.

I will create an experimental branch and let you know when I get something working and let you try it out and give feedback.

**Comment by juanfal** [comment]
Really clear! Thanks! Well it seems a could help myself using Chrome (I hate Google) but I'll do it until, well Safari/Mail couple works for me.

Never seen a so clear and precise explanation.  😀

Thanks!

**Comment by facelessuser** [comment]
Yeah, this took me forever to get to, but I added an option to disable the conversion from spaces to `&nbsp;`.  This is done per command.  Hopefully that helps.
