### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by Adarma** [facelessuser/ExportHtml#42]
Could you add an option to "Copy to Clipboard" in various [formats](https://msdn.microsoft.com/en-us/library/aa359736%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)?
Could it be done with the clipboard format set so that it will paste as coloured text rather than plaintext in supported target apps?

- Set RTF to the clipboard so it can be pasted to RTF aware apps.
- Set HTML to the clipboard as well so it can be pasted to HTML aware apps too.
- Set plaintext to the clipboard as well so it can be pasted to other apps.

**Comment by facelessuser** [comment]
> Could you add an option to "Copy to Clipboard" in various formats?

Probably not, but plain text to the clipboard is already available.

> Set RTF to the clipboard so it can be pasted to RTF aware apps.

I have no current plans to create a conversion to RTF.  I don't usually use this, and unless I start using RTF, there is no motivation for me to spend time on this.

> Set HTML to the clipboard as well so it can be pasted to HTML aware apps too.

We already can copy plain text to the clipboard on export, check the documentation.  If you are looking for a specially formatted HTML format in the clipboard to paste formatted HTML content instead of plain text HTML content, you probably will be waiting a while as for different systems (OSX, WINDOWS, MAC), this can be quite different, and I have no plans currently to implement a solution to work on all 3.

If you need to copy HTML content to the clipboard, I recommend exporting and opening in the webbrowser and copy from there.  This is what I currently do and it is sufficient for my needs.

> Set plain text to the clipboard as well so it can be pasted to other apps.

Already available.

**Comment by Adarma** [comment]
Yeah, fair enough,

I assumed it would be tricky due to cross platform compatibility.
